spring:
  application:
    name: social-media-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: ${AUTHORIZATION_SERVICE_URI}
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthentication
util:
  auth-address: ${AUTHORIZATION_SERVICE_URI}