services:
  postgres:
    container_name: user_service_db
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social-media-user-service
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - social-media-app-network
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
volumes:
  pg_data:

networks:
  social-media-app-network:
    driver: bridge