services:
  postgres:
    container_name: db
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - social-media-app-network
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/data
    networks:
      - social-media-app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social-media-app-network

volumes:
  pg_data:
  kafka_data:
  redis_data:

networks:
  social-media-app-network:
    driver: bridge