services:
  postgres:
    container_name: user_service_db
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social-media-user-service
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - social-media-app-network
  mysql:
    container_name: post_service_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=social-media-post-service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data
    networks:
      - social-media-app-network
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/data
    networks:
      - social-media-app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social-media-app-network

volumes:
  pg_data:
  mysql_data:
  kafka_data:
  redis_data:

networks:
  social-media-app-network:
    driver: bridge