spring:
  application:
    name: social-media-user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    default-schema: user
    schemas: user
    table: flyway_schema_history_user
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  devtools:
    livereload:
      port: 35730
server:
  port: 8081
utils:
  internal-secret-token: ${INTERNAL_SECRET_TOKEN}