spring:
  application:
    name: social-media-post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  flyway:
    schemas: post
    default-schema: post
    table: flyway_schema_history_post
  devtools:
    livereload:
      port: 35777
server:
  port: 8083
jwt:
  key: ${JWT_KEY}